<a href="https://colab.research.google.com/github/Setyaeva/-.-MySQ/blob/master/lin_al__DZ5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Найти с помощью NumPy SVD для заданной матрицы**

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [6]:
X=np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
print(f'Матрица X:\n{X}')

Матрица X:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [7]:
Y, Z, W = np.linalg.svd(X)

In [8]:
D = np.zeros_like(X, dtype=float)
D[np.diag_indices(min(X.shape))] = Z

In [9]:
print(f'Матрица Y:\n{Y}')
print(f'Матрица D:\n{D}')
print(f'Матрица V:\n{W.T}')

Матрица Y:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


2. **Для матрицы из предыдущего задания найти:**

а) евклидову норму;

б) норму Фробениуса.

In [15]:
# Евклидова норма

s1=np.linalg.norm(X, ord=2)
print(f"Евклидова норма для матрицы X:\n{s1}")

Евклидова норма для матрицы X:
8.824868854820444


In [17]:
# Норма Фробениуса

s2=np.linalg.norm(X, ord='fro')

print(f"Норма фробениуса для матрицы X:\n{s2}")

Норма фробениуса для матрицы X:
11.045361017187261
