<a href="https://colab.research.google.com/github/Setyaeva/-.-MySQ/blob/master/%D0%94%D0%BE%D0%B1%D1%80%D0%BE_%D0%BF%D0%BE%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_%D0%B2_Colaboratory!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Часть 1.**


**Задание 1.**

Исследовать на линейную зависимость: f1(x)=e^{x}, f2(x)=1, f3(x)=x+1, f4(x)=x-e^{x}.

*Ответ:* x-e^x=-(e^x)-(1)+(x+1), т.е. f_{4}(x)=-f_{1}(x)-f_{2}(x)+f_{3}(x), поскольку мы можем выразить один вектор, через линейную комбинацию остальных, данные векторы линейно зависимы.

**Задание 2.**

Исследовать на линейную зависимость: f1(x)=2, f2(x)=x, f3(x)=x^{2}, f4(x)=(x+1)^{2}

*Ответ:* Вектор $f_{4}(x)=(x+1)^2$  можем представить как: $f_{4}(x)=(x+1)^2=x^2+2, поскольку мы можем выразить один вектор, через линейную комбинацию остальных, данные векторы линейно зависимы.

**Задание 3.**

Найти координаты вектора x = (2, 3, 5)в базисе b1=(0, 0, 10), b2=(2, 0, 0), b3=(0, 1, 0)

x = 0.5b1 + b2 + 3b3  

*Ответ:* координаты (0.5, 1, 3)

**Задание 4.**

Найти координаты вектора 3x^{2}-2x+2

1.  в базисе x^{2}, x-1, 1
2.  в базисе x^{2}, x-1, 1



**Задание 5.**

Установить, является ли линейным подпространством:  

1.  совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;
    
2.  все векторы, являющиеся линейными комбинациями данных векторов



1.)Является линейным подпространством. Проверим на векторах:(a, 0, b) и (0, c, d).  Их сумма равна (a, c, b+d).

2) Также является линейным подпространством.

**Часть 2.**

**Задание 1.**

Найти скалярное произведение векторов x, y

1.   x=(0,-3, 6), y=(-4, 7, 9)
2.   x=(7, -4, 0, 1), y=(-3, 1, 11, 2)



1)

In [5]:
import numpy as np

In [3]:
x = np.array ([0,-3, 6])
y = np.array([-4, 7, 9])
x,y

(array([ 0, -3,  6]), array([-4,  7,  9]))

In [8]:
z=np.dot(x,y)
z

33

2)

In [9]:
x = np.array ([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
x,y

(array([ 7, -4,  0,  1]), array([-3,  1, 11,  2]))

In [10]:
z=np.dot(x,y)
z

-23

**Задача 2.**

Найти нормы векторов (4, 2, 4) и (12, 3, 4) и угол между ними.

In [2]:
from numpy.linalg import norm

In [6]:
a = np.array ([4, 2, 4])
b = np.array ([12, 3, 4])
a,b

(array([4, 2, 4]), array([12,  3,  4]))

In [13]:
print (f'Для вектора а =(4,2,4) манхеттенская норма: {norm(a,ord=1)}, евклидова норма: {norm(a, ord=2)}\n',
f'Для вектора b=(12,3,4) манхеттенская норма: {norm(b, ord=1)}, евклидова норма:{norm(b, ord=2)}\n', 
f'Угол между векторами a=(4,2,4) и b=(12,3,4): {np.arccos(np.dot(a, b)/(norm(a)*norm(b))):.2f}')

Для вектора а =(4,2,4) манхеттенская норма: 10.0, евклидова норма: 6.0
 Для вектора b=(12,3,4) манхеттенская норма: 19.0, евклидова норма:13.0
 Угол между векторами a=(4,2,4) и b=(12,3,4): 0.46
